### PR TITLE
Added some details to the README file about running locally.

### PR DESCRIPTION
**Pull request by waharnum**
I've added some basic notes to the README as a result of my own experimentation, which may be helpful to others trying to get a start. Merge if useful.

### CODE REVIEW

**Comment by jccr** [comment]
Hey Alan (@waharnum),

Thanks so much for looking into our project and trying it out! I very much appreciate your participation in the Readium org.

Everything looks great, but I have a thought about one thing:
You mention in the text that it's recommended to use an http-server.
There's an npm task that's in there 'npm run serve'
https://github.com/evidentpoint/r2-testapp-web/blob/master/package.json#L12

What do you think? Does that correlate here, and should it fit in?

**Comment by waharnum** [comment]
@jccr That makes perfect sense to me - I use `http-server` for quick static serving of projects, so didn't even check if there was a project equivalent.

**Comment by waharnum** [comment]
@jccr updated to reference the project's own NPM task for serving the `public` directory rather than another method.

**Comment by jccr** [comment]
Thanks so much!

**Comment by waharnum** [comment]
@jccr you're welcome - glad to be able to make a small contribution - this repo has been extremely helpful to me in the last few days as I was trying to get a deeper handle on the Readium codebase.

**Pull request merged**
